// Vue/Matheus Battisti/2_projeto_vue/src/components/Form.vue
<template>
  <form action="">
    <input type="text" v-model="nome"> <br>
    <input type="text" v-model="email">
    <input type="submit" value="Enviar" @click="enviarFormulario">
  </form>
  <p>{{ nome }} | {{ email }}</p>
</template>

<script>
import InputText from './InputText.vue';

export default {
  name: "Form",
  components: { InputText },
  data() {
    return {
      nome: null,
      email: null
    }
  },
  methods: {
    enviarFormulario(e) {
      e.preventDefault()

      const nome = this.nome
      const email = this.email

      console.log('Formulario Enviado')
      console.log('Nome: ' + nome)
      console.log('Email: ' + email)
    }
  }
};
</script>

// JavaScript/react/meu-projeto/src/components/Form.js
import { useState } from 'react'

function Form() {

    function CadastrarUsuario(e) {
        e.preventDefault()
        console.log(`Usuario cadastrado`)
        console.log(`Nome: ${name}`)
        console.log(`Senha: ${passworld}`)
    }

    const [name, setName] = useState()
    const [passworld, setPassworld] = useState()

    return (
        <div>
            <h1>Meu cadastro</h1>
            <form onSubmit={CadastrarUsuario}>
                <div>
                    <label htmlFor="nome">Nome:</label>
                    <input id="nome" type="text" placeholder="Digite o seu nome" onChange={(e) => setName(e.target.value)} />
                </div>

                <div>
                    <label htmlFor="senha">Senha:</label>
                    <input id="senha" type="passworld" placeholder="Digite a sua senha" onChange={(e) => setPassworld(e.target.value)} />
                </div>

                <div>
                    <input type='submit' value='Cadastrar' />
                </div>

            </form>
        </div>
    )   
}

export default Form
