// Curso Web-Moderno/vue/calculadora/src/components/Calculator.vue
<template>
  <div class="calculator">
    <display-vue :value="displayValue" />
    <button-vue label="AC" triple @onClick="clearMemory" />
    <button-vue label="/" operation @onClick="setOperation" />
    <button-vue label="7" @onClick="addDigit" />
    <button-vue label="8" @onClick="addDigit" />
    <button-vue label="9" @onClick="addDigit" />
    <button-vue label="*" operation @onClick="setOperation" />
    <button-vue label="4" @onClick="addDigit" />
    <button-vue label="5" @onClick="addDigit" />
    <button-vue label="6" @onClick="addDigit" />
    <button-vue label="-" operation @onClick="setOperation" />
    <button-vue label="1" @onClick="addDigit" />
    <button-vue label="2" @onClick="addDigit" />
    <button-vue label="3" @onClick="addDigit" />
    <button-vue label="+" operation @onClick="setOperation" />
    <button-vue label="0" double @onClick="addDigit" />
    <button-vue label="." @onClick="addDigit" />
    <button-vue label="=" operation @onClick="setOperation" />
  </div>
</template>

<script>
import DisplayVue from "./Display.vue";
import ButtonVue from "./Button.vue";

export default {
  name: "CalculatorContainer",
  data() {
    return {
      displayValue: "0",
      clearDisplay: false,
      operation: null,
      values: [0, 0],
      current: 0,
    };
  },
  components: { DisplayVue, ButtonVue },
  methods: {
    clearMemory() {
      Object.assign(this.$data, this.$options.data());
    },
    setOperation(operation) {
      if (this.current === 0) {
        this.operation = operation;
        this.current = 1;
        this.clearDisplay = true;
      } else {
        const equals = operation === "=";
        const currentOperation = this.operation;

        try {
          this.values[0] = eval(
            `${this.values[0]} ${currentOperation} ${this.values[1]}`
          );
          if (isNaN(this.values[0]) || !isFinite(this.values[0])) {
            this.clearMemory();
            return;
          }
        } catch (e) {
          this.$emit("onError", e);
          console.error(e);
        }

        this.values[1] = 0;
        this.displayValue = this.values[0];
        this.operation = equals ? null : operation;
        this.current = equals ? 0 : 1;
        this.clearDisplay = !equals;
      }
    },
    addDigit(n) {
      if (n === "." && this.displayValue.includes(".")) return;

      const clearDisplay = this.displayValue === "0" || this.clearDisplay;
      const currentValue = clearDisplay ? "" : this.displayValue;
      const displayValue = currentValue + n;

      this.displayValue = displayValue;
      this.clearDisplay = false;

      if (n !== ".") {
        const i = this.current;
        const newValue = parseFloat(displayValue);
        this.values[i] = newValue;
      }
    },
  },
};
</script>

<style>
.calculator {
  height: 320px;
  width: 235px;
  border-radius: 5px;
  overflow: hidden;

  display: grid;
  grid-template-columns: repeat(4, 20%);
  grid-template-rows: 1fr repeat(5, 48px);
}
</style>

// Curso Web-Moderno/react/calculadora/src/main/Calculator.jsx
import { Component } from "react";
import '../styles/Calculator.css'
import Button from '../components/Button'
import Display from "../components/Display";

const initialState = {
    displayValue: '0',
    clearDisplay: false,
    operation: null,
    values: [0, 0],
    current: 0
}

export default class Calculator extends Component {

    state = { ...initialState }

    constructor(props) {
        super(props)
        this.clearMemory = this.clearMemory.bind(this)
        this.setOperation = this.setOperation.bind(this)
        this.addDigit = this.addDigit.bind(this)
    }

    clearMemory() {
        this.setState({ ...initialState })
    }

    setOperation(operation) {
        if(this.state.current === 0) {
            this.setState({ operation, current: 1, clearDisplay: true})
        } else {
            const equals = operation === '='
            const currentOperation = this.state.operation

            const values = [...this.state.values]

            try {
                values[0] = eval(`${values[0]} ${currentOperation} ${values[1]}`)
                if (isNaN(values[0]) || !isFinite(values[0])) {
                    this.clearMemory()
                return
                }
            } catch(e) {
                values[0] = 0
            }
            
            values[1] = 0

            this.setState({
                displayValue: values[0],
                operation: equals ? null : operation,
                current: equals ? 0 : 1,
                clearDisplay: !equals,
                values
            })
        }
    }

    addDigit(n) {
        if(n === '.' && this.state.displayValue.includes('.')) return;


        const clearDisplay = this.state.displayValue === '0' || this.state.clearDisplay

        const currentValue = clearDisplay ? '' : this.state.displayValue
        const displayValue = currentValue + n
        this.setState({ displayValue, clearDisplay: false })

        if(n !== '.') {
            const i = this.state.current
            const newValue = parseFloat(displayValue)
            const values = [...this.state.values]
            values[i] = newValue
            this.setState({ values })
            console.log(values)
        }
    }

    render() {
        return (
            <div className="calculator">
                <Display value={this.state.displayValue}/>
                <Button label="AC" triple click={this.clearMemory} />
                <Button label="/" operation click={this.setOperation} />
                <Button label="7" click={this.addDigit} />
                <Button label="8" click={this.addDigit}  />
                <Button label="9" click={this.addDigit}  />
                <Button label="*" operation click={this.setOperation}  />
                <Button label="4" click={this.addDigit}  />
                <Button label="5" click={this.addDigit}  />
                <Button label="6" click={this.addDigit}  />
                <Button label="-" operation click={this.setOperation}  />
                <Button label="1" click={this.addDigit}  />
                <Button label="2" click={this.addDigit}  />
                <Button label="3" click={this.addDigit}  />
                <Button label="+" operation click={this.setOperation}  />
                <Button label="0" double click={this.addDigit} />
                <Button label="." click={this.addDigit}  />
                <Button label="=" operation click={this.setOperation}  />
            </div>
        )
    }
}
